### ISSUE TITLE
Test failure in core.event

### ISSUE THREAD

**Issue by roshanr95** [boostorg/compute#107]
Weird test failure in `core.event`

```
6/97 Test  #6: core.event .............................***Failed    0.03 sec
Running 2 test cases...
/compute/test/test_event.cpp:45: error in "event_callback": check callback_invoked == true failed [true != true]

*** 1 failure detected in test suite "TestEvent"
```

Sometimes it also fails with `false != true` which is understandable but `true != true` ?
##

**Comment by haahh** [comment]
I think it was fixed in https://github.com/boostorg/compute/commit/417cb03670adf4fa52dde2f0a6f0e4b89bf252ac (added a mutex and a condition_variable to ensure thread safety).
