### ISSUE TITLE
Problem using arbitrary struct as value parameter in compute::sort_by_key()

### ISSUE THREAD

**Issue by jesko42** [boostorg/compute#162]
Hello Kyle,

I tried to use compute::sort_by_key with a vector<float> as key and a struct like that

```
typedef struct
{
    float a;
    float v[20];
} imx;
vector<imx>
```

as the value (or payload).
But unfortunately I cannot use this struct, only basic data types like int, float, double or so ...
Browsing the code it looks not too difficult to extend the current behaviour ...

/Jesko

```
//--------------------------------------------------------- code snippet below
    std::vector<float> host_vector_keys(33);
    std::vector<imx> host_vector_payload(host_vector_keys.size());
    compute::vector<float> device_vector_keys = host_vector_keys;
    compute::vector<imx> device_vector_payload = host_vector_payload;
    compute::sort_by_key(device_vector_keys.begin(), device_vector_keys.end(), device_vector_payload.begin());
```
##

**Comment by jaytea** [comment]
Hi there,

did you make any progress regarding this issue? Now I have to get some timings of my program and it would be nice to be able to use OpenCL for the sorting there.
Best regards
jay

**Comment by kylelutz** [comment]
Sorry, haven't made much progress on this. I've been busy with the peer-review process and getting the library ready for inclusion in Boost (which should hopefully happen soon). Getting this issue fixed is definitely still on my TODO list.

**Comment by jaytea** [comment]
Ok, that is a very good reason. I'll just use the cpu for sorting for now. Thanks for your work and good luck with the peer review.

**Comment by haahh** [comment]
Fixed by https://github.com/boostorg/compute/issues/701.
