### ISSUE TITLE
Add test for fill() with every built-in type

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#219]
Add a test for the `fill()` algorithm with every built-in type (e.g. `int_`, `float_`, `uint4_`). This will provide good code coverage for the `fill()` algorithm and for the built-in type wrappers. Use the [`BOOST_AUTO_TEST_CASE_TEMPLATE`](http://www.boost.org/doc/libs/1_56_0/libs/test/doc/html/utf/user-guide/test-organization/auto-test-case-template.html) macro to repeat the same test code with every type.

**Comment by haahh** [comment]
It can be closed, see https://github.com/boostorg/compute/issues/461.

**Comment by kylelutz** [comment]
Thanks!
