### ISSUE TITLE
Add performance benchmarks for AMD's Bolt

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#220]
Add performance benchmarks for AMD's [Bolt](https://github.com/HSA-Libraries/Bolt) library. Similar to the `perf_thrust_*` benchmarks which are used for comparing the performance of Boost.Compute against NVIDIA's Thrust library.

**Comment by haahh** [comment]
Commit https://github.com/haahh/compute/commit/309a201a61efdb6fca86131ae896dbb5d6a68745 adds first Bolt perf test. I will add all possible tests and then make PR.

Bolt requires C++11, so performance tests for Bolt are build only if BOOST_COMPUTE_USE_CPP11 option is enabled. if BOOST_COMPUTE_HAVE_BOLT option is on and BOOST_COMPUTE_USE_CPP11 is off, warning message is printed. I couldn't find any better way to communicate this requirement, is there?

Bolt requires certain Boost libraries: thread system date_time chrono.

**Comment by haahh** [comment]
Can be closed, see https://github.com/boostorg/compute/pull/453.

**Comment by kylelutz** [comment]
Awesome! Thanks!
