### ISSUE TITLE
Intermittent test_search failure on Travis-CI

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#245]
The following test failure occurs occasionally on Travis-CI:
```
test_search: /home/travis/build/kylelutz/compute/test/test_search.cpp:45: void compute_test::search_int::test_method(): Assertion `iter == vectort.begin() + 10' failed.
Running 2 test cases...
unknown location(0): fatal error in "search_int": signal: SIGABRT (application abort requested)
*** 1 failure detected in test suite "TestSearch"
```

See the build here: https://travis-ci.org/kylelutz/compute/jobs/33041316

We should investigate this (potentially run it on the Intel CPU OpenCL implementation under valgrind).

**Comment by haahh** [comment]
I got almost the same problem (but in `test_search_n.cpp`) with clang on Travis-CI (https://travis-ci.org/boostorg/compute/builds/79994943). I check it on my PC (AMD HD7770) on `master` and this error occurs both with clang and g++.  It does not happen every time.

```
Running 2 test cases...
test_search_n: /home/jakub/git/compute/test/test_search_n.cpp:37: void compute_test::search_int::test_method(): Assertion `iter == vectort.begin() + 10' failed.
unknown location(0): fatal error in "search_int": signal: SIGABRT (application abort requested)

*** 1 failure detected in test suite "TestSearchN"

```

**Comment by haahh** [comment]
OK, I know where the bug is.  I'll push a fix in a few minutes.

**Comment by haahh** [comment]
This was fixed in https://github.com/boostorg/compute/pull/511. Can be closed.

**Comment by kylelutz** [comment]
Closed. Thanks!
