### ISSUE TITLE
command_queue::command_queue problem with versions

### ISSUE THREAD

**Issue by WojciechMula** [boostorg/compute#283]
I've intel-based system (output from clinfo.exe):

Number of platforms:                 2
  Platform Profile:              FULL_PROFILE
  Platform Version:              OpenCL 1.2 
  Platform Name:                 Intel(R) OpenCL
  Platform Vendor:               Intel(R) Corporation
  Platform Profile:              FULL_PROFILE
  Platform Version:              OpenCL 2.0 
  Platform Name:                 Experimental OpenCL 2.0 CPU Only Platform
  Platform Vendor:               Intel(R) Corporation

As we see there are two devices, supporting different OpenCL versions, however headers shipped with the newest SDK from Intel defines CL_VERSION_2_0. This is the problem, because command_queue::command_queue selects an initialization code using defines, and if it is called on device supporting version 1.2 then strange errors happen in a drivers. When I manually edited library code to use initialization for 1.2 everyting works ok.

Maybe API version should be obtained from a device info? Or is it a problem in vendor SDK?
##

**Comment by haahh** [comment]
It should be fixed by https://github.com/boostorg/compute/commit/60f4b31bdd374e088eb26262c9b7970a08f9ab8c.
