### ISSUE TITLE
Full async interface

### ISSUE THREAD

**Issue by bkchr** [boostorg/compute#303]
Hi, 
I'm working for a project where we need full async communication with OpenCL, but we also want to use some of your basic functions like "transform". So I created a first implementation for a "transform_async", that's not so complicated at all, but to get real async operations working some internal changes are required as well. Buffer and kernel objects now can save events, these events are passed to OpenCL to ensure that an operation on a buffer is executed after the previous operation is finished. 
What do you think in overall about this idea? Do you maybe would implement some parts different? 
I hope that we can find a way, that this features finds a way into your repo.

Here is a link to my repo: https://github.com/bastiankoe/compute
##

**Comment by Ulfgard** [comment]
I would like to rise awareness to this issue again as I also stumbled upon it recently. Here a simplified use case in an out-of-order queue:
    
    using namespace boost::compute;
    vector<float> a,b;
    event e = copy_async(b.begin(),b.end(),a.begin()).get_event();
    fill(b.begin(),b.end(),0);//bad without synchronization

I would propose a simple interface where the wait_list is appended as extra parameter to all functions (snychronous and asynchronous):

    fill(b.begin(),b.end(),0,system::default_queue(),wait_list(e));

**Comment by kylelutz** [comment]
@Ulfgard Yeah, currently the Boost.Compute algorithms do not fully support out-of-order command queues.

Adding an additional `wait_list` parameter to all of the current functions would be a large undertaking, and instead I think it would be more useful to support this in a potential "version 2" of the algorithms API (potentially with an executors-style interface). I'd be interested to hear your thoughts on this.

**Comment by Ulfgard** [comment]
@kylelutz I can understand that it is a large undertaking. I myself decided to copy your implementation of copy_on_device, added the wait_list parameter and used this for my library. The only problem is that as soon as you change some of the internals, this will break, but I guess i have to live with that for now.

I am not sure how you would redesign the API. One could see the command_queue already as an executor that handles task scheduling, the only thing that has to be done from user side is adding the dependencies to the tasks that are scheduled. Note that the interface design in the current discussion of the standard does not allow for explicit handling of dependencies but only for indirect handling through futures and then() statements. I am not sure about the current state of the discussion but i think at some point scheduling a task after some other task was handled similar to

    when_all(future1,future2,...futureN).then(executor,myTaskFunction);

But this is not straight forward to implement on GPUs. In simple threading we can wait to add myTaskFunction to the executor until all dependencies are ready, but on GPUs we have the latency of the command queue which makes this approach inefficient. Further, I am unsure how i would transform a call to std::copy or std::fill to something that fits this interface. The standard library can encode this via a lambda function replacing myTaskFunction. On GPUs we do not have such syntax sugar...
