### ISSUE TITLE
Sort_by_key fails at 6144 elements or more

### ISSUE THREAD

**Issue by shehzan10** [boostorg/compute#343]
It looks like sort_by_key fails at any size greater than or equal to 6144 elements.
The gist has the code I used to test this: https://gist.github.com/shehzan10/2d34a612aa3ee44a145b (its a modifies sort_vector example).

Here is the relevant output:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::compute::opencl_error> >'
terminate called recursively
  what():  Out of Resources
Aborted (core dumped)
```

Other observations:
- This only happens if `compute::less<type>()` or `compute::greater<type>()` are specified.
- This bug does not affect sort with or without the direction specified.

This bug may possibly be related to #275.
##

**Comment by haahh** [comment]
Fixed, see https://github.com/boostorg/compute/pull/619.
