### ISSUE TITLE
Add stable_sort_by_key() algorithm

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#377]
Add a `stable_sort_by_key()` algorithm which works like `sort_by_key()` but keeps the keys/values in stable order.

**Comment by pavanky** [comment]
@kylelutz can't this be closed because of #573 ?

**Comment by kylelutz** [comment]
Yup, closed!

**Comment by Bulat-Ziganshin** [comment]
stable_sort_by_key() should be listed here: http://www.boost.org/doc/libs/1_61_0_b1/libs/compute/doc/html/boost_compute/reference.html

**Comment by kylelutz** [comment]
@Bulat-Ziganshin Thanks for catching that, I've made a pull request to update that: #601

**Comment by Bulat-Ziganshin** [comment]
i don't know how html is generated from qbk, but f.e. stable_sort is mentioned in 3 places of http://www.boost.org/doc/libs/1_61_0_b1/libs/compute/doc/html/boost_compute/reference.html

**Comment by kylelutz** [comment]
Yeah, the other mentions come from globing the headers with `include/boost/compute/algorithm/*.hpp`, so it doesn't have to mention `boost/compute/stable_sort_by_key.hpp` explicitly.
