### ISSUE TITLE
Cray compile error with version /opt/cray/nvidia/319.37-1_1.0402.1285.1.2.gem

### ISSUE THREAD

**Issue by Belcourt** [boostorg/compute#406]
On Tue, Dec 30, 2014 at 4:15 PM, Belcourt, Kenneth kbelco@sandia.gov wrote:
I ran into a compilation problem on another Cray system:

"boost/include/boost/compute/type_traits/type_name.hpp", line 79: error:
         class
         "boost::compute::detail::type_name_traitboost::compute::char_" has
         already been defined
 BOOST_COMPUTE_DEFINE_BUILTIN_TYPE_NAME_FUNCTION(char)
 ^

Commenting out line 79 got me past the error.

Interesting. My best guess is that this occurs because "cl_char" and
"char" are actually synonymous on that platform which leads us to
specialize the same template twice. Would you mind submitting a bug to
the issue tracker [1] for this?

I didn't encounter this error on newer Cray systems.
##

**Comment by robertdfrench** [comment]
Hi @Belcourt , is this still an ongoing issue? If so, which compiler are you using?
