### ISSUE TITLE
Improving boost::compute::extents functionalities

### ISSUE THREAD

**Issue by keryell** [boostorg/compute#428]
By developing an application with the great Boost.Compute, I just figured out that even if extents looks like a STL container it is not even a limited one, which in unfortunate when writing something like this:

  boost::compute::extents<n> global { ... };
  boost::compute::extents<n> local { ... };
  std::clog << "Launching kernel with { ";
  for (auto v : global)
    std::clog << v << ", ";
  std::clog << "workitems with workgroups of { ";
  for (auto v : local)
    std::clog << v << ", ";
  std::clog << "} workitems" << std::endl;
because there is no begin()/end() method for example.

If we change extents to inherit from array<> instead of having an array member it should work, such as:
template<size_t N>
class extents : public boost::array<size_t, N>;

I made a similar approach for range<> and id<> in SYCL based on this class:
https://github.com/keryell/triSYCL/blob/12055c1be2b243c82d4e45bfced9cac125a43e32/include/CL/implementation/sycl-implementation.hpp#L279
I started to experiment it in Boost.Compute but I do not know how to write it in pre-C++11, without parent constructor inlining, etc... (SYCL requires C++11 at least, which may not be the case of Boost.Compute.)

We can also add a lot of interesting extensions on boost::compute::extents, for example to compute the work-group geometry by just writing global/local, etc.

Thank you.
##

**Comment by kylelutz** [comment]
That's a good idea. I don't think inheritance is the right approach here, but I'll add `begin()` and `end()` methods to `extents<N>` which allow access to the underlying array values and enable the use of a for-range loop over an `extents<N>` object.

**Comment by kylelutz** [comment]
Implemented in PR #429.
