### ISSUE TITLE
CMakeLists.txt uses BOOST_COMPUTE_ in options

### ISSUE THREAD

**Issue by marbre** [boostorg/compute#465]
I have created an ebuild of BoostCompute for the [Gentoo Science Overlay](https://github.com/gentoo-science/sci/tree/master/dev-libs/boost-compute). We use cmake for installation and I would like to enable some of the options provided in the `CMakeLists.txt ` via Gentoo specific use flags. BoostCompute defines most options with `option(BOOST_COMPUTE_HAVE_`. Is the `BOOST_COMPUTE_` prefix really necessary? For us it would be easier if the prefix is dropped, since with than could just functions like `$(cmake-utils_use_has cuda CUDA)` (see [devmanual](https://devmanual.gentoo.org/eclass-reference/cmake-utils.eclass/)), which adds `-DHAVE_CUDA=ON` if the cuda use flag is added and `-DHAVE_CUDA=OFF` otherwise.

I would like to hear what you think about this. If it is acceptable to drop the prefix, I can also send a pull request.

**Comment by ddemidov** [comment]
Boost.Compute is header only, so why would one need the use flags? The options control what examples/perf tests are build, do those need to be installed system-wide?

**Comment by marbre** [comment]
Well, we also got an `examples` use flag which allows the user to install them. But no, it it only affects the examples there is no real need. As it seems that also the tests are unaffected (just took a quick look), I think it's not worth the effort of dropping the prefix.

**Comment by kylelutz** [comment]
Yeah, the flags in the `CMakeLists.txt` mainly affect the examples, benchmarks, and tests that get compiled. The "real" Boost.Compute code is all header-only and isn't dependent on any of those flags.

**Comment by marbre** [comment]
Thanks for clarification.
