### ISSUE TITLE
Please add reserve() to wait_list

### ISSUE THREAD

**Issue by piotrwyderski** [boostorg/compute#466]
wait_list is internally based on std::vector (the m_events field),
but there is no way to request a memory block reservation even
if the size is known, which leads to unnecessary reallocations.
Please add the reserve() method which would simply forward its
argument(s -- a variadic template-based forwarder perhaps?) to
m_events.

**Comment by kylelutz** [comment]
Good idea, this shouldn't be too difficult to do.

**Comment by kylelutz** [comment]
Implemented in PR #574.
