### ISSUE TITLE
Get the platform from a given device

### ISSUE THREAD

**Issue by piotrwyderski** [boostorg/compute#467]
There is no simple, user-accessible way to ask the default device
about the platform it belongs to, i.e. the "default platform", despite
the fact that the requested functionality is available, but defined
in the private section, namely the device_platform() static method.
The user it then required to effectively clone that method:

default_device.get_info<cl_platform_id>(CL_DEVICE_PLATFORM)

This code could be moved to the device itself, which would then allow
the user to ask about the platform of any device, not just the default.

**Comment by kylelutz** [comment]
There is already a [`device::platform()`](http://boostorg.github.io/compute/boost/compute/device.html#idp51956272-bb) method so you should be able to just do `boost::compute::system::default_device().platform()`. Or am I misunderstanding?
