### ISSUE TITLE
Update Travis-CI to use new container infrastructure

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#481]
We should update Boost.Compute to use the new container based Travis-CI builders. See: http://docs.travis-ci.com/user/migrating-from-legacy/.

**Comment by roshanr95** [comment]
A PR(https://github.com/travis-ci/apt-package-whitelist/pull/750) has been opened a few hours ago to add fglrx to the package whitelist. Also, the whitelist contains boost 1.55 and not 1.48. Is that OK?

**Comment by kylelutz** [comment]
That's good to hear! Once that goes in I think we should be able to rewrite the `travis.yml` file to use the new infrastructure. And testing against Boost 1.55 is fine, 1.48 is getting pretty old now (though it's probably still good to remain compatible with it).

**Comment by haahh** [comment]
I think this issue can be closed.
