### ISSUE TITLE
Is boost::compute optimizes Arm ?

### ISSUE THREAD

**Issue by ya1gaurav** [boostorg/compute#499]
ARM has neon optimizations. Does boost::compute provide some way for these optimizations?

**Comment by haahh** [comment]
If by optimized for ARM you mean its algorithms benefits from fact that CPU and GPU are on the same chip etc., then no. Though, Boost.Compute should run on ARM, both its CPU and GPU.

FindOpenCL.cmake is even extended to work on ARM Mali GPUs https://github.com/boostorg/compute/commit/d5fc3170f8185e8e58b82c4b8229b3bef489048f.

**Comment by ya1gaurav** [comment]
ok I got your point. Thanks.
However, there is one more question, as compute is not part of official boost release. Is this module used in many projects? Is there some list of projects published?

**Comment by pavanky** [comment]
We use it in [arrayfire](https://github.com/arrayfire/arrayfire) for a bunch of vector algorithms.

**Comment by ya1gaurav** [comment]
Ok thanks, If more projects can post usage. We can publish Boost Compute user projects here. It will help spreading more information.
By the way thanks for fast response & kudos to Boost Compute.
Please mark this post as question & close.
