### ISSUE TITLE
system::default_device() fails to respect BOOST_COMPUTE_DEFAULT_DEVICE_TYPE for non gpu devices

### ISSUE THREAD

**Issue by pisto** [boostorg/compute#505]
This is because the type of the device id is a bitmask, but the test used are equalities. This means that if the device type is cpu but it is also default, it's type will be `CL_DEVICE_TYPE_DEFAULT|CL_DEVICE_TYPE_CPU != boost::compute::device::cpu`.

**Comment by haahh** [comment]
What do you mean by that? You cannot set CPU as default device? Because for me `export BOOST_COMPUTE_DEFAULT_DEVICE_TYPE=CPU` works. 

Can you point the file and line where `device.type()` is compared to `boost::compute::device::cpu / gpu / accelerator` instead of `&`?

**Comment by haahh** [comment]
Did you mean this [include/boost/compute/system.hpp#L229](https://github.com/boostorg/compute/blob/master/include/boost/compute/system.hpp#L229)?

**Comment by pisto** [comment]
It may work for you if your CPU device is not the default one. I don't know how to mark system-wide my devices as defaults. Anway, I can find these occurrencies:
```
include/boost/compute/algorithm/count_if.hpp:41:    if(device.type() & device::cpu){
include/boost/compute/algorithm/reduce.hpp:175:    if(device.type() & device::cpu){
include/boost/compute/algorithm/detail/scan.hpp:33:    if(device.type() & device::cpu){
include/boost/compute/algorithm/detail/find_extrema.hpp:40:    if(count < 64 || (device.type() & device::cpu)){
include/boost/compute/system.hpp:229:                    if (!(device.type() & device::gpu))
include/boost/compute/system.hpp:233:                    if (!(device.type() & device::cpu))
include/boost/compute/system.hpp:250:            if(device.type() & device::gpu){
include/boost/compute/system.hpp:259:            if(device.type() & device::cpu){
test/test_command_queue.cpp:166:       device.type() == boost::compute::device::gpu){
example/list_devices.cpp:31:            if(device.type() & compute::device::gpu)
example/list_devices.cpp:33:            else if(device.type() & compute::device::cpu)
example/list_devices.cpp:35:            else if(device.type() & compute::device::accelerator)
```

I suggest you clear CL_DEVICE_TYPE_DEFAULT inside device::type().

**Comment by pisto** [comment]
Updated comment, a few times, see previous.

**Comment by haahh** [comment]
Aaaaa, OK, now I get it.

**Comment by haahh** [comment]
> I suggest you clear CL_DEVICE_TYPE_DEFAULT inside device::type() here > https://github.com/boostorg/compute/blob/master/include/boost/compute/device.hpp#L158

I think there's not need for that. We just need to change `if (device.type() != device::gpu)` to  `if (!(device.type() & device::gpu))` (and so on), like you did:

```
include/boost/compute/system.hpp:229:                    if (!(device.type() & device::gpu))
include/boost/compute/system.hpp:233:                    if (!(device.type() & device::cpu))
include/boost/compute/system.hpp:250:            if(device.type() & device::gpu){
include/boost/compute/system.hpp:259:            if(device.type() & device::cpu){
```

**Comment by haahh** [comment]
You can make pull request with these changes (in `system.hpp` and you should also change `device.type() == boost::compute::device::gpu` to `device.type() & boost::compute::device::gpu` in `test/test_command_queue.cpp:166`).

**Comment by haahh** [comment]
This can be closed, see https://github.com/boostorg/compute/pull/508.
