### ISSUE TITLE
CL_MAP_WRITE_INVALIDATE_REGION is a valid flag in 1.2

### ISSUE THREAD

**Issue by pisto** [boostorg/compute#530]
No need for this ifdef https://github.com/boostorg/compute/blob/master/include/boost/compute/command_queue.hpp#L88

**Comment by haahh** [comment]
Based on this https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/enums.html#cl_map_flags and this https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/enums.html#cl_map_flags, I think ifdef is needed, but it should be `CL_VERSION_1_2` instead of `CL_VERSION_2_0`.

**Comment by pisto** [comment]
Yeah.

**Comment by haahh** [comment]
Thanks ;) I'll fix it soon.

**Comment by haahh** [comment]
Can be closed - see https://github.com/boostorg/compute/pull/533.
