### ISSUE TITLE
Add program constructor that accepts a vector of strings

### ISSUE THREAD

**Issue by svenstaro** [boostorg/compute#536]
The official OpenCL C++ bindings provide a program constructor that accepts a vector of strings for sources. Presumably this would be used to load a list of files into the vector. As it stands in boost compute, the way to obtain the same behavior is making a really long concatenated string and pass that instead.

**Comment by kylelutz** [comment]
Yeah, that shouldn't be too hard. And like you said, the best way currently is to create a single concatenated string.

**Comment by kylelutz** [comment]
Implemented in PR #539.

**Comment by svenstaro** [comment]
Sweet!
