### ISSUE TITLE
Update documentation before next Boost release

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#561]
Now that Boost.Compute is an official Boost library and will be included in Boost 1.61, we need to update the documentation to reflect this.

Currently there are a few locations where we describe Boost.Compute as ["not yet an offical Boost library"](http://www.boost.org/doc/libs/master/libs/compute/doc/html/boost_compute/getting_started.html).

**Comment by haahh** [comment]
Are you working on this today? I can delete those notes tomorrow.
4 mar 2016 00:45 "Kyle Lutz" <notifications@github.com> napisał(a):

**Comment by kylelutz** [comment]
Yeah, I've got some work in progress which clean up the docs. Should be ready soon.

**Comment by haahh** [comment]
Ok 👍
4 mar 2016 19:48 "Kyle Lutz" <notifications@github.com> napisał(a):

**Comment by haahh** [comment]
``reduce_by_key`` is not listed in API overview.

**Comment by haahh** [comment]
I think http://boostorg.github.io/compute/ need to be rebuilt.

**Comment by kylelutz** [comment]
Looks like since becoming a sub-module in the Boost super-project I lost being able to build just the Boost.Compute documentation by itself :-(.

I wonder if we should just have a re-direct from http://boostorg.github.io/compute to http://boost.org/doc/libs/develop/libs/compute/doc/html/index.html (which is automatically updated).
