### ISSUE TITLE
Copy 2 vectors into a single pair vector

### ISSUE THREAD

**Issue by shehzan10** [boostorg/compute#578]
I have 2 vectors of equal size. Say A and B.
I want to create an vector of a `struct { type a; type b}` and copy the contents of A and B into this vector.
I tried using transform, but couldn't figure it out.

Here's what the C++11 code would look like (note: using std::pair instead of struct)
```
std::vector<std::pair<T, T> > X(N);
std::transform(A.begin(), A.end(),
                       B.begin(),
                       std::back_inserter(X),
                       [](T a, T b) { return std::make_pair(a, b); }
                      );
```

How can I use the `back_inserter` and lamba in boost compute.
Can I use `std::pair` as a type for `compute::vector`?

Thanks!

**Comment by haahh** [comment]
Check out
https://github.com/boostorg/compute/blob/master/test/test_zip_iterator.cpp
test case called "copy".
5 kwi 2016 17:48 "Shehzan Mohammed" <notifications@github.com> napisał(a):

**Comment by shehzan10** [comment]
Thanks for that.
Is it possible to use std::pair/tuple instead of `boost::tuple`?

**Comment by haahh** [comment]
I'm not 100% sure, but I think it's possible to use `std::pair`/`std::tuple` and `std::make_pair`/`std::make_tuple`. You can check [test_pair.cpp](https://github.com/boostorg/compute/blob/38ba1c54479869c6ad6d2ea1f828e6d113bc5ab9/test/test_pair.cpp).

**Comment by haahh** [comment]
@shehzan10 Did it work for you?

**Comment by shehzan10** [comment]
Yeah it did work with std::pair. But since the pair was being used in sort_by_key, we ran into other issues and dropped the pair and used a workaround.
This issue can be closed.
