### ISSUE TITLE
Sort and Sort By Key fail beyond certain size for custom types on NVIDIA and AMD

### ISSUE THREAD

**Issue by shehzan10** [boostorg/compute#586]
I was working with std::pair sorting. The kernel fails with `Out of Resources` error.
This only happens on NVIDIA and AMD. Intel works fine.

A standalone code to test the bug is attached (rename to .cpp).
Compilation command:

```
g++ -std=c++11 sort_vector.cpp -o sort_vector -I /path/to/compute/include/ -lOpenCL -lm
```

Gist: https://gist.github.com/shehzan10/938d22d2ed68baf4b48ad85f66a612f1
Attachment: [sort_vector.txt](https://github.com/boostorg/compute/files/230548/sort_vector.txt)
##

**Comment by pavanky** [comment]
Problem location:
 https://github.com/boostorg/compute/blob/master/include/boost/compute/algorithm/detail/insertion_sort.hpp#L137

**Comment by haahh** [comment]
This is related to https://github.com/boostorg/compute/issues/343. We do not have comparison sort implementation yet. I'll add before July.

**Comment by pavanky** [comment]
Welp, forgot that we reported the other issue as well.

**Comment by dot3bumpmap** [comment]
I get the same error when trying to sort vector of any custom type (and obviously custom compare func) with length >  4096 elements. Is there currently any workaround for this?

**Comment by haahh** [comment]
@dot3bumpmap Currently, there is not a universal workaround for this. I'm working on a comparison sort for GPUs. We also need `radix_sort` to be rewritten using `meta_kernel` class.

**Comment by haahh** [comment]
Fixed, see https://github.com/boostorg/compute/pull/619.

**Comment by dot3bumpmap** [comment]
Awesome work! Solves an issue for me.
