### ISSUE TITLE
Add default constructor for discrete_distribution

### ISSUE THREAD

**Issue by kylelutz** [boostorg/compute#612]
Add a default constructor to [`discrete_distribution`](http://www.boost.org/doc/libs/develop/libs/compute/doc/html/boost/compute/discrete_distribution.html). Also support the case `first == last` when calling the current iterator range constructor. See the documentation for [`std::discrete_distribution`](http://en.cppreference.com/w/cpp/numeric/random/discrete_distribution/discrete_distribution).

**Comment by haahh** [comment]
Can be closed.
