### ISSUE TITLE
BOOST_COMPUTE_ADAPT_STRUCT crash with transform

### ISSUE THREAD

**Issue by Naviee** [boostorg/compute#618]
This code always crashes once transform is called.

```
BOOST_COMPUTE_FUNCTION(bool, modify, (test::clParticle a),
{
	a.y += 0.5;
	return true;
});

boost::compute::transform	(gpu_particles.begin(), gpu_particles.end(), gpu_particles.begin(), modify, 
```

**Comment by Naviee** [comment]
Btw. I get a "Build Programm failure" exception when debugging the whole thing.

**Comment by haahh** [comment]
Try
```
BOOST_COMPUTE_FUNCTION(bool, modify, (clParticle a),
{
    a.y += 0.5;
    return true;
});
```

**Comment by haahh** [comment]
Also `BOOST_COMPUTE_ADAPT_STRUCT(test::clParticle, clParticle, (x, y, z, ox, oy, oz, vx, vy, vz)` is missing one bracket at the end.

**Comment by Naviee** [comment]
Thank you haahh but this does not compile anymore then because clParticle is undeclared (makes sense because it's not in the global namespace right?!)

Concerning your second note, thanks, I fixed this in the issue code but in my own code it's correctly there.

**Comment by haahh** [comment]
In the transform operation you are trying to assign `bool` to `clParticle`, that's not right.

**Comment by haahh** [comment]
Yes, sorry. My first comment is wrong.

**Comment by haahh** [comment]
Your function should look like this:
```cpp
BOOST_COMPUTE_FUNCTION(test::clParticle, modify, (test::clParticle a),
{
    a.y += 0.5;
    return a;
});
```

**Comment by Naviee** [comment]
Darn, yes that makes sense! I didn't have in mind that the result is assigned. Totally my fault! I will try that right away.

**Comment by haahh** [comment]
When you get "Build Programm failure" error, try compiling with option 
`-DBOOST_COMPUTE_DEBUG_KERNEL_COMPILATION`. That way, Boost.Compute will print the build log and you'll see what's wrong.

**Comment by Naviee** [comment]
Thanks! With the correct return type the crash is gone. :) And thanks for the tip about the BOOST_COMPUTE_DEBUG_KERNEL_COMPILATION option. Will do!

Cheers

**Comment by haahh** [comment]
Hi Naviee, why did you reopen this issue?

**Comment by Naviee** [comment]
Argh, sorry, I had a problem with the code after I updated to the latest version of this repository but then I noticed an error in my code. At that time I had already reopened it and forgot to close it again. Please ignore it (not me please.. :).
