### ISSUE TITLE
compute::vector<> get/set value using custom queue

### ISSUE THREAD

**Issue by dPavelDev** [boostorg/compute#643]
When I have to get/set some values from some index from vector using custom queue, I forced to use compute::copy function, not **[]** or **at** members. I can't use convenient methods to access elements! 

I think, it is necessary to provide method "set_default_queue(queue)" and public method get_default_queue() for all containers.

Also, is it right to wright code similar to?
```cpp
struct my {
    int x, y;
}

BOOST_COMPUTE_ADAPT_STRUCT...
compute::array<my, 42> a;
a[7].x = 6; // this line (get my struct, edit member, set value)
```

**Comment by haahh** [comment]
IMHO, it's worth considering. However, that would require `buffer_value<T>` class to store `command_queue`.

If we don't want to store `command_queue` in `vector`, then we can at least provide `at()` method which takes `command_queue` as its 2nd argument.

**Comment by dPavelDev** [comment]
> If we don't want to store command_queue object in vector (and other containers), then we can at least provide at() method which takes command_queue as its 2nd argument. 

It's rather good idea for getting value. But how to set value? Operator = uses own command queue

**Comment by haahh** [comment]
It's easy. Method `at()` does not return reference to the value itself but rather a `buffer_value<T>` object that wraps that value. If we modify `buffer_value<T>` to store `command_queue` object then [here](https://github.com/boostorg/compute/blob/master/include/boost/compute/detail/buffer_value.hpp#L121) we can use that queue instead of making a new one.

**Comment by haahh** [comment]
And just because I'm curious: Can you tell me where you use such a small array in GPU computing? I mean, in most cases `operator[]` is not even needed since in GPGPU you operate on rather large sets of data, not single values.

**Comment by dPavelDev** [comment]
Yes, you're right, operator[] needs rarely. For example, I have change only one value. When I build BVH-tree on GPU using my own algorithm, tree root value (only tree root) has undefined value. There are two ways: write kernel to modify only the one value or change this from host.

**Comment by haahh** [comment]
OK, thanks. I've just remembered, you can always do this:
```cpp
compute::array<int_> a(context);
(a.begin() + 7).write(6, queue)
```

**Comment by dPavelDev** [comment]
Read and write members with custom queue in buffer_iterator. Excellent! But nothing about it in documentation.
