### ISSUE TITLE
Compile using (/for) an older OpenCL API version

### ISSUE THREAD

**Issue by amirshavit** [boostorg/compute#647]
Currently, if the cl.h header supports newer API versions (say CL_VERSION_2_1), boost::compute uncontrollably uses that API version. If I run my compiled binary on a different system, with an older opencl library, the binary will fail to load due to missing exports in the dll/so.

I see there are run-time version checks (`device.check_version(...)`) but they aren't helpful for this problem.

An easy solution could be if the cl.hpp (of boost::compute) could #undef those (after `#include <.../cl.h>`), something like -

``` c++
#if defined(BOOST_COMPUTE_AVOID_CL_VERSION_2_0) && defined(CL_VERSION_2_0)
#undef CL_VERSION_2_0
#endif
...
```
##

**Comment by haahh** [comment]
Yeah, IIRC that was mentioned a few times. Basically, you postulate to add macros for selecting the newest supported OpenCL version instead of using the newest defined in used `cl.h`, yes?

**Comment by amirshavit** [comment]
Yes.

An alternative form (based on your suggestion) -
```c++
#if defined(BOOST_COMPUTE_MAX_CL_VERSION)
// ...
#  if defined(BOOST_COMPUTE_MAX_CL_VERSION < 20) && defined(CL_VERSION_2_0)
#    undef CL_VERSION_2_0
#  endif
// ...
#endif
```

I'm not sure if `#undef`-ing is the so-called right solution, but it sure it the fastest.

**Comment by haahh** [comment]
I think the right way would be to define internal macros based on OpenCL version macros and options set by a user, and replace OpenCL version marcos (like `CL_VERSION_2_0`) with them.

**Comment by amirshavit** [comment]
I agree.  Should I open a pull request or is this something for further consideration?

**Comment by haahh** [comment]
If you want to do this, then do this and open a pull request and wait for @kylelutz to accept it. If you don't have time for this, then you have to wait for me or @kylelutz to code this, but I don't have time to do that this month.

**Comment by haahh** [comment]
Fixed - https://github.com/boostorg/compute/pull/699.
