### ISSUE TITLE
Max buffer memory - CL_DEVICE_MAX_MEM_ALLOC_SIZE

### ISSUE THREAD

**Issue by ppacory** [boostorg/compute#679]
Platform: NVIDIA CUDA
	Vendor:  NVIDIA Corporation
	Version: OpenCL 1.2 CUDA 7.0.0

	Number of devices: 1
	-------------------------
		Name: GeForce GTX TITAN X
		Version: OpenCL C 1.2 
		Max. Compute Units: 24
		Local Memory Size: 47 KB
		Global Memory Size: 12287 MB
		Max Alloc Size: 3071 MB
		Max Work-group Size: 1024
		Max Work-item Dims: (1024 1024 64)
	-------------------------

Here my problem,
when i try to allocate more than 3071MB with compute::copy 
i've got this error

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::compute::opencl_error> >'
  what():  Memory Object Allocation Failure

here a ref for the problem : 
https://devtalk.nvidia.com/default/topic/498004/opencl-6gb-memory-problem-get-error-message-at-4-2gb-of-memory/

**Comment by haahh** [comment]
Well, it is said that max alloc size is 3071 MB, so it seems normal that you get error when you try to allocate more in one buffer.

**Comment by haahh** [comment]
I guess you create one object of class `boost::compute::vector`, which in the end is just a wrapper class for an OpenCL buffer, and then you copy data from host (from some `std::vector`) to that device vector. Is that correct?

**Comment by ppacory** [comment]
how to allocate more than one buffer ?
boost::compute copy ??

**Comment by ppacory** [comment]
#include <vector>
#include <algorithm>
#include <boost/compute.hpp>

namespace compute = boost::compute;

int main()
{
    // get the default compute device
    compute::device gpu = compute::system::default_device();

    // create a compute context and command queue
    compute::context ctx(gpu);
    compute::command_queue queue(ctx, gpu);

    // generate random numbers on the host
    std::vector<uint32_t> host_vector1(1000000000);
    std::vector<uint32_t> host_vector2(1000000000);

    // create vector on the device
    compute::vector<uint32_t> device_vector1(host_vector1.size(), ctx);
    compute::vector<uint32_t> device_vector2(host_vector2.size(), ctx);

    // copy data to the device
    compute::copy( host_vector1.begin(), host_vector1.end(), device_vector1.begin(), queue );
    compute::copy( host_vector2.begin(), host_vector2.end(), device_vector2.begin(), queue );

    // problem of memory at this point ...

    return 0;
}

**Comment by Ulfgard** [comment]
Hi,

your single buffers are still exceeding the allowed maximum size by the device. Remove a zero and it will work.
________________________________

**Comment by haahh** [comment]
Vector of 1000000000 `int32_t`s takes ~3814 MB, which is obviously more than 3071 MB. You just need to allocate less memory. Replace 

```cpp
// generate random numbers on the host
std::vector<uint32_t> host_vector1(1000000000);
std::vector<uint32_t> host_vector2(1000000000);
```

with

```cpp
// generate random numbers on the host
std::vector<uint32_t> host_vector1(700000000);
std::vector<uint32_t> host_vector2(700000000);
```

It should help. The problem occurs when copying because allocating memory for buffer is a lazy operation, so it's performed when buffer is used for the first time (in your case - during copying). You can close. It's not a Boost.Compute-related issue.

**Comment by ppacory** [comment]
ok thks for your help

**Comment by ppacory** [comment]
just another question :  
with those memory size on a nvidia titanX
Global Memory Size: 12287 MB
Max Alloc Size: 3071 MB
I never arrived to address more than 4Go, with different buffer or context
Is there a way to override that ?
