### ISSUE TITLE
Optionally enforce algorithm to pick the default device

### ISSUE THREAD

**Issue by keryell** [boostorg/compute#692]
When using some weird devices or debugging OpenCL stacks & compilers, it does not make sense to run the application on anything else.

If I correctly understand `find_default_device()`algorithm in https://github.com/boostorg/compute/blob/master/include/boost/compute/system.hpp#L210 on using the very handy`BOOST_COMPUTE_DEFAULT_` variables, when some criteria cannot be fulfilled we fall-back on returning the first GPU found, etc.

So I'd like to add another variable environment for example (`BOOST_COMPUTE_DEFAULT_ENFORCE`? Bike-sheding welcome! :-) ) to change the selection algorithm to throw when a `BOOST_COMPUTE_DEFAULT_` variable is set but the criteria cannot be fulfilled.

Any comment?

I can write a PR.

**Comment by haahh** [comment]
How throwing an exception would be helpful in such situations? I mean if you forget to set environment  variables so `find_default_device()` picks device you want to use, you can always forget about adding `BOOST_COMPUTE_DEFAULT_ENFORCE.

**Comment by haahh** [comment]
I mean, if it's not about forgetting to set environment variables, how otherwise would it be possible there is no device you want to use?

**Comment by kylelutz** [comment]
@keryell I think I understand what you're getting at. If you could submit a PR with the proposal that would be great! Thanks!

**Comment by haahh** [comment]
I'm waiting for that PR ;)

**Comment by keryell** [comment]
Yes I know. :-(
But I am quite busy with a lot of deadlines. Such as the Khronos face-to-face meeting next week.
Perhaps see you there?

**Comment by haahh** [comment]
> Yes I know. :-( But I am quite busy with a lot of deadlines. 

Sure :) I understand. Just remember it's assigned to you.

> Such as the Khronos face-to-face meeting next week. Perhaps see you there?

Maybe you'll hear me :), but it seems I won't be there in person.

**Comment by ddemidov** [comment]
Do you guys mean something like https://github.com/ddemidov/compute/commit/a7aa6cb564e3176d844c6fa4eb23cf448dcb502c?

**Comment by haahh** [comment]
Yes, I think so :) @keryell?

**Comment by haahh** [comment]
Implemented in https://github.com/boostorg/compute/issues/712.

**Comment by keryell** [comment]
Amazing!
@ddemidov you are motivating me to procrastinate... :-)
