### ISSUE TITLE
shrink_to_fit() doesn't seem to do anything

### ISSUE THREAD

**Issue by BrettRyland** [boostorg/compute#732]
Perhaps I'm doing something wrong, but shrink_to_fit() doesn't seem to do anything. For example, with an appropriate `context` and `queue` the following

    compute::vector<double> device_vec(10000, context);
    std::cout << "Size and capacity are " << device_vec.size() << " and " << device_vec.capacity() << "\n";
    device_vec.clear();
    std::cout << "Size and capacity after clearing are " << device_vec.size() << " and " << device_vec.capacity() << "\n";
    device_vec.shrink_to_fit(queue);
    queue.finish();
    std::cout << "Size and capacity after shrinking to fit are " << device_vec.size() << " and " << device_vec.capacity() << "\n";

gives

    Size and capacity are 10000 and 10000
    Size and capacity after clearing are 0 and 10000
    Size and capacity after shrinking to fit are 0 and 10000

which can lead to unexpected memory allocation problems.

**Comment by jszuppe** [comment]
Indeed, it does nothing: https://github.com/boostorg/compute/blob/master/include/boost/compute/container/vector.hpp#L449

**Comment by jszuppe** [comment]
However, `resize(size_type size, command_queue &queue)` does work.

**Comment by BrettRyland** [comment]
Resizing behaves as expected from the STL, i.e. the number of elements in the vector are changed, but the capacity is never reduced, so that's not an issue.  
While the request to reduce the capacity is non-binding, it would be nice if it was fulfilled. ;-)

**Comment by jszuppe** [comment]
> Resizing behaves as expected from the STL, i.e. the number of elements in the vector are changed, but the capacity is never reduced, so that's not an issue.

Oh, yeah, you're right.

> While the request to reduce the capacity is non-binding, it would be nice if it was fulfilled. ;-)

Sure :) I guess nobody's used it or needed it before. If want you can fix it on your own and add a pull request. Otherwise, I can implement it tomorrow or this weekend.

**Comment by BrettRyland** [comment]
I'm fairly new to boost::compute, so it's probably best if someone else fixes it. No hurry though. I only came across the problem while experimenting with how many and how large a vector I could allocate on a device https://stackoverflow.com/questions/44547038/allocating-large-vectors-in-boostcompute

**Comment by jszuppe** [comment]
Yes, I know :) I answered your questions.
