### ISSUE TITLE
How to include preprocessor directives in BOOST_COMPUTE_STRINGIZE_SOURCE

### ISSUE THREAD

**Issue by HolyWu** [boostorg/compute#735]
I want to use #if or #ifdef in the OpenCL source code. But the macro won't receive the preprocessor directives and stringize them since the directives will be resolved first by the preprocessor before compilation begins. Is there any way to solve it? Thanks.

**Comment by jszuppe** [comment]
If you want keep using macro, then no. However, you can just put your code in a string.

**Comment by jszuppe** [comment]
I'd recommend using raw string literal.

**Comment by HolyWu** [comment]
I see, thanks.
