### ISSUE TITLE
Wrong sort results using customized compare

### ISSUE THREAD

**Issue by antibes0415** [boostorg/compute#774]
Hi. I want to sort 64-bit long variates according to their upper 32 bit value.
Here is the code:

`  
BOOST_COMPUTE_FUNCTION(bool, compareSampleKeys, (cl_ulong a, cl_ulong b), {
    return (a >> 32) < (b >> 32);
  });
  // cl::Buffer *m_dev_sampleKeys;
  boost::compute::buffer cbSampleKeys((*m_dev_sampleKeys)());

  boost::compute::buffer_iterator<cl_ulong> iter =
    boost::compute::make_buffer_iterator<cl_ulong>(cbSampleKeys, 0);

  boost::compute::sort(
    iter,
    iter + m_nbSamples,
    compareSampleKeys,
    m_compute_queue
  );
`

Don't know why lots values are modified after sorting. In my case, all numbers are unique and there turn out to be many repetitive numbers after sorting. I tried not using customized compare, and that won't modify the values.

**Comment by rosenrodt** [comment]
I have the same issue with compute::sort() too. I tried a vector of custom struct. Unique keys in, duplicate keys out.

**Comment by jszuppe** [comment]
Fixed in #803
