### ISSUE TITLE
Qualify make_zip_iterator in algorithm/transform.hpp

### ISSUE THREAD

**Issue by Javanater** [boostorg/compute#789]
Currently, transform calls make_zip_iterator. This is ambiguous if you include boost/compute/algorithm/transform.hpp and boost/iterator/zip_iterator.hpp in the same compilation unit. I was able to fix it by changing the make_zip_iterator calls to ::boost::compute::make_zip_iterator.

**Comment by kylelutz** [comment]
Thanks for the report!

Fixed in #790.

**Comment by Javanater** [comment]
Thank you!
