### ISSUE TITLE
opengl_create_shared_context cl_gl_sharing_extension references are in quotes

### ISSUE THREAD

**Issue by Javanater** [boostorg/compute#791]
In interop/opengl/context.hpp, opengl_create_shared_context initializes the variable cl_gl_sharing_extension to "cl_APPLE_gl_sharing" for APPLE, and "cl_khr_gl_sharing" for all other platforms. The problem is that the cl_gl_sharing_extension variable is in quotes, so the function will always fail with a unsupported_extension_error. See lines 79, 121, and 132.

**Comment by kylelutz** [comment]
Hi @Javanater,

I'm not sure I fully understand the issue. Can you explain problem you're encountering further (potentially with a reproducible test case demonstrating the failure)?

Thanks!

**Comment by jszuppe** [comment]
I think it was fixed in https://github.com/boostorg/compute/pull/773.

**Comment by Javanater** [comment]
It was fixed in #773. Sorry, and Thanks.
