### ISSUE TITLE
Will it run on intel sandyBridge mobile processor...

### ISSUE THREAD

**Issue by coderboyisongithub** [boostorg/compute#814]
I have intel core -i3 sandy bridge proc.With integerated GPU..I dont have external GPU embedded on mother board...So can I use this library even if i don't have Nvidia or AMD GPUs?

**Comment by jszuppe** [comment]
It should. I don't know if the performance would be great as, IIRC, we did not optimise for Intel's iGPUs.

**Comment by coderboyisongithub** [comment]
If i want to gather information from GPU memory , like values of shader variable running there with Opengl ...  Can I do so?any possibility?

**Comment by keryell** [comment]
You will probably need to use the OpenGL interoperability mode of OpenCL provided by Boost.Compute...
Boost.Compute is a library to ease OpenCL usage. So you "just" need to write the OpenCL kernel you want on your GPU.

**Comment by coderboyisongithub** [comment]
!! I have to write the whole kernel down?


Sent from Mail for Windows 10

**Comment by keryell** [comment]
Boost libraries are about C++ programming.
But I agree that it would be nice to have a telepathy mode where you just think at your problem and then the solution is implemented... :-)
