### ISSUE TITLE
Cl.h not found.. compile error..

### ISSUE THREAD

**Issue by coderboyisongithub** [boostorg/compute#821]
![image](https://user-images.githubusercontent.com/24197201/51917797-6be4b600-2408-11e9-9550-2b19d863ff70.png)

I get following error while compilation...Do I also have to setup opencl on system...or anything else..
I thought boost have opencl support built~in

Visual studio 2012
win 10 x64
intel sandy-bridge i3

**Comment by jszuppe** [comment]
Yes, you need to install OpenCL.

**Comment by coderboyisongithub** [comment]
I downloaded opencl 2.1 API from github...Now this gives following error
![image](https://user-images.githubusercontent.com/24197201/51921543-b61d6580-240f-11e9-923b-22246302b890.png)
