### ISSUE TITLE
how about android devices 

### ISSUE THREAD

**Issue by lligen** [boostorg/compute#856]
hello,

is this project support cross compile for android devices?

**Comment by lligen** [comment]
such as Qualcomm/mtk GPU.

**Comment by ksrikar1234** [comment]
> such as Qualcomm/mtk GPU.

Yes it will

**Comment by ksrikar1234** [comment]
> hello,
> 
> is this project support cross compile for android devices?

Yes it will. If ur android mobile has OpenCL driver support. Some vendor do not include one. Samsung and few others however does include OpenCL driver in their OS. U should check if normal OpenCL code runs or not. If yes u can use boost compute.
